### ISSUE TITLE
Inject environment variables via option

### ISSUE THREAD

**Issue by acerv** [linux-test-project/runltp-ng#11]
Some tests requires a particular SUT configuration and that can be done via environment variables. The idea is that we can add a `--env VAR0=var0:VAR1=var1` option that permits to run tests with specific environment variables.

**Comment by pevik** [comment]
@acerv `TMPDIR` does not work. Setting the temporary directory is important on SUT. The only way to set it `--tmp-dir`, but that requires that directory is also on host. That might require to create this directory and symlink in case SUT has mounted specific directory which is not on host => too complicated, tmpdir should be 2: host tmpdir and SUT tmpdir.

**Comment by acerv** [comment]
@pevik we can inherit ``TMPDIR`` from bash and use it for LTP initialization, while ``--tmp-dir`` is only used for host.
