### ISSUE TITLE
Support writing into dmesg over ssh

### ISSUE THREAD

**Issue by pevik** [linux-test-project/runltp-ng#5]
There is mark in dmesg when run locally:

```
$ sudo ./runltp-ng  -r smoketest
...
# in dmesg
[194762.002188] ./runltp-ng[12038]: starting test fork01 (fork01)
[194762.009388] ./runltp-ng[12038]: starting test time01 (time01)
...
```
I don't see any dmesg message, but the ssh user set is root:
```
$ ./runltp-ng --sut ssh:host=myhost -r smoketest
```

NOTE: it'd be also great if mark could be for `-c foo` (single command), that does not work even locally.

**Comment by acerv** [comment]
`/dev/kmsg` is not set on SUT but only on localhost. Do we need to set also SUT kmsg?

**Comment by pevik** [comment]
We are testing SUT, thus only dmesg on SUT is relevant (regardless SUT is on localhost or accessed via ssh). Whole point of this mark is which test caused particular kernel oops/message.
